# Migration for composite database indices
#
# This migration adds composite indices that are critical for query performance
# but cannot be auto-generated by Django from model definitions.
#
# These indices are documented in views.py comments where they are used.
# Single-column indices are defined via db_index=True in models for maintainability.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glossary", "0001_initial"),
    ]

    operations = [
        # Entry model composite indices
        # Composite index for soft-delete filtering combined with date range queries
        # Used in: EntryViewSet.get_queryset() for created_after/created_before filtering
        # See: backend/glossary/views.py line 165
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(
                fields=["is_deleted", "created_at"],
                name="glossary_en_is_del_created_idx",
            ),
        ),
        # EntryDraft model composite indices
        # Composite index for EntryViewSet.list() query pattern:
        # Entry.filter(drafts__is_published=True).distinct() with ordering
        # Used in: EntryViewSet.get_queryset() line 147
        migrations.AddIndex(
            model_name="entrydraft",
            index=models.Index(
                fields=["entry", "is_published", "created_at"],
                name="glossary_en_entry_pub_created_idx",
            ),
        ),
        # Composite index for EntryDraftViewSet.list() default filtering:
        # filter(is_published=False) with ordering by -created_at
        # Used in: EntryDraftViewSet.get_queryset() line 578
        migrations.AddIndex(
            model_name="entrydraft",
            index=models.Index(
                fields=["is_published", "created_at"],
                name="glossary_en_pub_created_idx",
            ),
        ),
        # Composite index for author filtering with ordering
        # Used in: EntryDraftViewSet.get_queryset() for author filtering (line 545)
        # and eligibility="own" queries (line 548)
        migrations.AddIndex(
            model_name="entrydraft",
            index=models.Index(
                fields=["author", "is_published", "created_at"],
                name="glossary_en_author_pub_created_idx",
            ),
        ),
        # Composite index for draft history queries
        # Used in: EntryDraftViewSet.history() line 811
        migrations.AddIndex(
            model_name="entrydraft",
            index=models.Index(
                fields=["entry", "is_deleted", "created_at"],
                name="glossary_en_entry_del_created_idx",
            ),
        ),
        # Comment model composite indices
        # Note: The generic foreign key (content_type, object_id) was removed
        # in a previous migration. Comment now uses a direct ForeignKey to EntryDraft.
        # Composite index for reply ordering
        # Used in: CommentViewSet queryset ordering by created_at with parent filtering
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["parent", "created_at"],
                name="glossary_co_parent_created_idx",
            ),
        ),
        # Term model composite indices
        # Composite index for search queries with soft-delete filtering
        # Used in: TermViewSet.get_queryset() for search on text_normalized (line 95)
        migrations.AddIndex(
            model_name="term",
            index=models.Index(
                fields=["is_deleted", "text_normalized"],
                name="glossary_te_del_text_norm_idx",
            ),
        ),
        # Note: Notification model's composite index ["user", "is_read", "-created_at"]
        # is already defined in the model's Meta.indexes and will be included in
        # the initial migration automatically.
    ]
