# Generated by Django 5.1.4 on 2025-10-10 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glossary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrydraft",
            name="replaces_draft",
            field=models.ForeignKey(
                blank=True,
                help_text="The draft that this draft replaces in the version history",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replaced_by",
                to="glossary.entrydraft",
            ),
        ),
    ]
