# Generated by Django 5.2.7 on 2025-10-05 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entryversion',
            name='endorsed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entryversion',
            name='endorsed_by',
            field=models.ForeignKey(blank=True, help_text='Domain expert who endorsed this version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endorsed_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name_normalized',
            field=models.CharField(db_index=True, default='', editable=False, max_length=100),
        ),
    ]
