# Generated by Django 5.1.4 on 2025-10-17 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("glossary", "0002_add_replaces_draft_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="active_draft",
        ),
    ]
