# Generated by Django 5.2.10 on 2026-01-13 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glossary", "0003_add_okta_id_to_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Tables already exist from migration 0001 (auto-created ManyToMany tables)
        # We use SeparateDatabaseAndState to update state without creating tables
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Database: tables already exist from migration 0001
                # Indexes will be added later via AddIndex operations
                # No database operations needed here since tables and fields already exist
            ],
            state_operations=[
                # State: create models in migration state with all fields
                # (fields already exist in database from migration 0001)
                migrations.CreateModel(
                    name="EntryDraftApprover",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "entrydraft",
                            models.ForeignKey(
                                db_column="entrydraft_id",
                                on_delete=django.db.models.deletion.CASCADE,
                                to="glossary.entrydraft",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                db_column="user_id",
                                on_delete=django.db.models.deletion.CASCADE,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "glossary_entry_draft_approvers",
                    },
                ),
                migrations.CreateModel(
                    name="EntryDraftRequestedReviewer",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "entrydraft",
                            models.ForeignKey(
                                db_column="entrydraft_id",
                                on_delete=django.db.models.deletion.CASCADE,
                                to="glossary.entrydraft",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                db_column="user_id",
                                on_delete=django.db.models.deletion.CASCADE,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "glossary_entry_draft_requested_reviewers",
                    },
                ),
            ],
        ),
        migrations.RemoveIndex(
            model_name="comment",
            name="glossary_co_parent_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="entry",
            name="glossary_en_is_del_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="entrydraft",
            name="glossary_en_entry_pub_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="entrydraft",
            name="glossary_en_pub_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="entrydraft",
            name="glossary_en_author_pub_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="entrydraft",
            name="glossary_en_entry_del_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="term",
            name="glossary_te_del_text_norm_idx",
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["draft", "is_deleted", "created_at"],
                name="gl_co_draft_del_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["draft", "parent", "is_deleted", "created_at"],
                name="gl_co_draft_parent_del_created",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["draft", "is_resolved", "created_at"],
                name="gl_co_draft_resolved_created",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["is_resolved", "created_at"], name="gl_co_resolved_created_idx"),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(
                fields=["term", "perspective", "is_deleted"],
                name="glossary_en_term_persp_del_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(fields=["term", "is_deleted"], name="glossary_en_term_del_idx"),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(fields=["perspective", "is_deleted"], name="glossary_en_persp_del_idx"),
        ),
        migrations.AddIndex(
            model_name="perspectivecurator",
            index=models.Index(fields=["user", "is_deleted"], name="glossary_pc_user_del_idx"),
        ),
        migrations.AddIndex(
            model_name="perspectivecurator",
            index=models.Index(fields=["perspective", "is_deleted"], name="glossary_pc_persp_del_idx"),
        ),
        # Cannot alter ManyToManyField to add through parameter - use SeparateDatabaseAndState
        # Database: tables already exist and are correct, no changes needed
        # State: update field definitions to include through parameter
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Database operations: do nothing, tables already exist correctly
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="entrydraft",
                    name="approvers",
                    field=models.ManyToManyField(
                        blank=True,
                        related_name="approved_drafts",
                        through="glossary.EntryDraftApprover",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                migrations.AlterField(
                    model_name="entrydraft",
                    name="requested_reviewers",
                    field=models.ManyToManyField(
                        blank=True,
                        help_text="Users specifically requested to review this draft",
                        related_name="requested_reviews",
                        through="glossary.EntryDraftRequestedReviewer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="entrydraft",
            index=models.Index(
                fields=["is_archived", "is_published", "created_at"],
                name="gl_en_arch_pub_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="entrydraft",
            index=models.Index(
                fields=["entry", "is_published", "is_deleted", "published_at"],
                name="gl_en_entry_pub_del_pubat",
            ),
        ),
        migrations.AddIndex(
            model_name="entrydraft",
            index=models.Index(fields=["entry", "is_deleted"], name="gl_en_entry_del_idx"),
        ),
        migrations.AddIndex(
            model_name="entrydraft",
            index=models.Index(
                fields=["author", "is_deleted", "created_at"],
                name="gl_en_author_del_created",
            ),
        ),
        # Indexes already created in SeparateDatabaseAndState above
        migrations.AddIndex(
            model_name="entrydraftapprover",
            index=models.Index(fields=["entrydraft", "user"], name="gl_ed_approvers_draft_user_idx"),
        ),
        migrations.AddIndex(
            model_name="entrydraftrequestedreviewer",
            index=models.Index(fields=["entrydraft", "user"], name="gl_ed_reviewers_draft_user_idx"),
        ),
    ]
