# Generated by Django 5.1.4 on 2026-01-10 23:41
# Manually edited to preserve existing indexes from 0002_add_composite_indices.py

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glossary", "0003_add_okta_id_to_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Use SeparateDatabaseAndState because the through tables already exist
        # from the initial migration. We only need to update Django's state and add indexes.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="EntryDraftApprover",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "entrydraft",
                            models.ForeignKey(
                                db_column="entrydraft_id",
                                on_delete=django.db.models.deletion.CASCADE,
                                to="glossary.entrydraft",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                db_column="user_id",
                                on_delete=django.db.models.deletion.CASCADE,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "glossary_entry_draft_approvers",
                    },
                ),
                migrations.CreateModel(
                    name="EntryDraftRequestedReviewer",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "entrydraft",
                            models.ForeignKey(
                                db_column="entrydraft_id",
                                on_delete=django.db.models.deletion.CASCADE,
                                to="glossary.entrydraft",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                db_column="user_id",
                                on_delete=django.db.models.deletion.CASCADE,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "glossary_entry_draft_requested_reviewers",
                    },
                ),
                migrations.AlterField(
                    model_name="entrydraft",
                    name="approvers",
                    field=models.ManyToManyField(
                        blank=True,
                        related_name="approved_drafts",
                        through="glossary.EntryDraftApprover",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                migrations.AlterField(
                    model_name="entrydraft",
                    name="requested_reviewers",
                    field=models.ManyToManyField(
                        blank=True,
                        help_text="Users specifically requested to review this draft",
                        related_name="requested_reviews",
                        through="glossary.EntryDraftRequestedReviewer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            database_operations=[
                # Tables already exist, just add indexes
                migrations.RunSQL(
                    sql="CREATE INDEX IF NOT EXISTS gl_ed_approvers_draft_user_idx ON glossary_entry_draft_approvers(entrydraft_id, user_id);",
                    reverse_sql="DROP INDEX IF EXISTS gl_ed_approvers_draft_user_idx;",
                ),
                migrations.RunSQL(
                    sql="CREATE INDEX IF NOT EXISTS gl_ed_reviewers_draft_user_idx ON glossary_entry_draft_requested_reviewers(entrydraft_id, user_id);",
                    reverse_sql="DROP INDEX IF EXISTS gl_ed_reviewers_draft_user_idx;",
                ),
            ],
        ),
        # Note: Keeping existing indexes from 0002_add_composite_indices.py
        # They are still needed and complement the new indexes being added
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["draft", "is_deleted", "created_at"],
                name="gl_co_draft_del_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["draft", "parent", "is_deleted", "created_at"],
                name="gl_co_draft_parent_del_created",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["draft", "is_resolved", "created_at"],
                name="gl_co_draft_resolved_created",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["is_resolved", "created_at"], name="gl_co_resolved_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(
                fields=["term", "perspective", "is_deleted"],
                name="glossary_en_term_persp_del_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(
                fields=["term", "is_deleted"], name="glossary_en_term_del_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(
                fields=["perspective", "is_deleted"], name="glossary_en_persp_del_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="perspectivecurator",
            index=models.Index(
                fields=["user", "is_deleted"], name="glossary_pc_user_del_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="perspectivecurator",
            index=models.Index(
                fields=["perspective", "is_deleted"], name="glossary_pc_persp_del_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entrydraft",
            index=models.Index(
                fields=["is_archived", "is_published", "created_at"],
                name="gl_en_arch_pub_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="entrydraft",
            index=models.Index(
                fields=["entry", "is_published", "is_deleted", "published_at"],
                name="gl_en_entry_pub_del_pubat",
            ),
        ),
        migrations.AddIndex(
            model_name="entrydraft",
            index=models.Index(
                fields=["entry", "is_deleted"], name="gl_en_entry_del_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entrydraft",
            index=models.Index(
                fields=["author", "is_deleted", "created_at"],
                name="gl_en_author_del_created",
            ),
        ),
        # Indexes for through tables are added in SeparateDatabaseAndState above
    ]
