# Generated by Django 5.1.4 on 2025-10-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glossary", "0003_remove_active_draft_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrydraft",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
