# Generated by Django 5.1.4 on 2025-11-22 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glossary", "0006_add_pagination_indices"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="comment",
            name="glossary_co_ct_obj_res_idx",
        ),
        migrations.RemoveIndex(
            model_name="comment",
            name="glossary_co_parent_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="entry",
            name="glossary_en_is_del_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="entrydraft",
            name="glossary_en_entry_pub_ts_idx",
        ),
        migrations.RemoveIndex(
            model_name="entrydraft",
            name="glossary_en_pub_ts_idx",
        ),
        migrations.RemoveIndex(
            model_name="entrydraft",
            name="glossary_en_author_pub_ts_idx",
        ),
        migrations.RemoveIndex(
            model_name="entrydraft",
            name="glossary_en_entry_del_ts_idx",
        ),
        migrations.RemoveIndex(
            model_name="term",
            name="glossary_te_del_text_norm_idx",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="object_id",
        ),
        migrations.AddField(
            model_name="comment",
            name="draft",
            field=models.ForeignKey(
                blank=True,
                help_text="The draft this comment is attached to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="glossary.entrydraft",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
