# Generated by Django 5.1.4 on 2025-11-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glossary", "0008_make_draft_field_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrydraft",
            name="is_archived",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether this draft has been archived (unpublished drafts older than 1 month)",
            ),
        ),
    ]
