# Generated by Django 5.1.4 on 2025-11-22 21:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glossary", "0009_add_archived_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="mentioned_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users mentioned in this comment via @mention",
                related_name="mentioned_in_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
