# Generated by Django 5.2.3 on 2025-06-15 12:09

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0002_alter_definition_options_alter_domain_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': [django.db.models.functions.text.Lower('text')]},
        ),
        migrations.AlterModelTable(
            name='term',
            table='glossary_term',
        ),
    ]
